<#
PowerShell helper to create .env and deploy PersonalFinance contract to a network.
Usage: Open PowerShell in the repo root then:
  cd onchain
  .\deploy_helper.ps1

The script will:
 - Prompt for RPC URL and PRIVATE_KEY (private key is read securely)
 - Create a `.env` file in the `onchain` folder
 - Run `npm install --legacy-peer-deps` if node_modules missing
 - Run `npx hardhat run --network sepolia scripts/deploy_pf.js`

Note: Do NOT share your private key. This script writes it to a local `.env` file.
#>

Set-StrictMode -Version Latest

Write-Host "=== FinanceChain onchain deploy helper ===" -ForegroundColor Cyan

$cwd = Split-Path -Path $MyInvocation.MyCommand.Definition -Parent
Set-Location $cwd

# prompt for RPC URL
$rpc = Read-Host "Enter RPC_URL (e.g. https://eth-sepolia.g.alchemy.com/v2/KEY)"
if ([string]::IsNullOrWhiteSpace($rpc)) {
    Write-Host "RPC_URL is required. Aborting." -ForegroundColor Red
    exit 1
}

# prompt for private key securely
Write-Host "Enter PRIVATE_KEY (will not echo). It must start with 0x..." -ForegroundColor Yellow
$secure = Read-Host -AsSecureString
if (-not $secure) {
    Write-Host "PRIVATE_KEY is required. Aborting." -ForegroundColor Red
    exit 1
}
# convert secure string to plain
$ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
try {
    $priv = [Runtime.InteropServices.Marshal]::PtrToStringAuto($ptr)
} finally {
    if ($ptr -ne [IntPtr]::Zero) {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
}

# write .env file
$envPath = Join-Path $cwd '.env'
"# Auto-generated by deploy_helper.ps1`nRPC_URL=$rpc`nPRIVATE_KEY=$priv" | Out-File -FilePath $envPath -Encoding utf8 -Force
Write-Host ".env file created at: $envPath" -ForegroundColor Green

# install deps if needed
if (-not (Test-Path (Join-Path $cwd 'node_modules'))) {
    Write-Host "Installing npm dependencies (this may take a while)..." -ForegroundColor Cyan
    npm install --legacy-peer-deps
    if ($LASTEXITCODE -ne 0) { Write-Host "npm install failed" -ForegroundColor Red; exit 1 }
} else {
    Write-Host "node_modules exists, skipping npm install." -ForegroundColor Gray
}

# run deploy
Write-Host "Deploying to network 'sepolia' using Hardhat..." -ForegroundColor Cyan
npx hardhat run --network sepolia scripts/deploy_pf.js
if ($LASTEXITCODE -ne 0) { Write-Host "Hardhat deploy failed" -ForegroundColor Red; exit 1 }

Write-Host "Deployment script finished." -ForegroundColor Green
Write-Host "If successful, copy the deployed contract address printed above into Frontend/index.html as window.PERSONAL_FINANCE_CONTRACT = '0x...';" -ForegroundColor Yellow

# end
